name: Docker Security Validation

on:
  workflow_dispatch:

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test Container
        run: |
          snyk container monitor test-image \
            --org=jharoldev \
            --severity-threshold=high \
            --app-vulns=false \
            --file=Dockerfile
