name: Snyk Dockerfile Analysis

on:
  workflow_dispatch:  # Permite ejecución manual

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Snyk Container Analysis
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: |
            --severity-threshold=low
            --org=jharoldev
            --json-file-output=scan-results.json
