name: Snyk Container Analysis

on:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app-image .

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Container Test
        run: snyk container test my-app-image --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
