name: Snyk Container Analysis

on:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app-image .

      - name: Snyk Auth
        run: echo "${{ secrets.SNYK_TOKEN }}" | docker run --rm -i snyk/snyk-cli auth

      - name: Run Snyk Container Analysis
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e "SNYK_TOKEN=${SNYK_TOKEN}" snyk/snyk-cli test my-app-image --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
