name: Snyk Container Security Scan

on:
  workflow_dispatch:
    inputs:
      severity_threshold:
        description: 'Nivel de severidad (low/medium/high)'
        required: true
        default: 'low'
        type: choice
        options:
          - low
          - medium
          - high

jobs:
  container-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build -t test-image .
      
      - name: Run Snyk Container Scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: test-image
          args: |
            --file=Dockerfile
            --severity-threshold=${{ inputs.severity_threshold }}
            --docker-skip-base-image-check
