name: Snyk Container Security Scan

on:
  workflow_dispatch:
    inputs:
      severity_threshold:
        description: 'Nivel de severidad (low/medium/high)'
        required: true
        default: 'low'
        type: choice
        options:
          - low
          - medium
          - high

jobs:
  container-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Verify Dockerfile exists
        run: |
          pwd
          ls -la
          echo "Verificando ubicación del Dockerfile..."
          find . -name "Dockerfile" -type f
      
      - name: Build Docker Image
        run: |
          if [ -f "Dockerfile" ]; then
            docker build -t test-image .
          else
            echo "Error: Dockerfile no encontrado"
            exit 1
          fi
      
      - name: Run Snyk Container Test
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: test-image
          args: |
            --file=Dockerfile
            --severity-threshold=${{ inputs.severity_threshold }}
            --docker-skip-base-image-check
            --project-name=test-image
            --org=jharoldev
            --monitor
          
      - name: Generate Security Report
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: test-image
          args: |
            --file=Dockerfile
            --json > snyk-container-report.json
            --org=jharoldev
          
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-security-report
          path: snyk-container-report.json
