name: CI/CD Pipeline with Trivy

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image exists in Docker Hub
        id: check-image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}"
          if docker pull $IMAGE_NAME; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
          
      - name: Build and Push Docker Image
        if: env.exists == 'false'
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --push .

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin

      - name: Create directory for scan reports
        run: mkdir -p anchore-reports

      - name: Scan Image with Trivy
        run: |
          ./bin/trivy image ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --format json --output anchore-reports/scan-report.json

      - name: Upload Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports
          path: ./anchore-reports
