name: CI/CD Pipeline with Trivy

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image exists in Docker Hub
        id: check-image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}"
          if docker pull $IMAGE_NAME; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
          
      - name: Build and Push Docker Image
        if: env.exists == 'false'
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --push .

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin

      - name: Create directory for scan reports
        run: mkdir -p anchore-reports

      - name: Scan Image with Trivy
        id: trivy-scan
        run: |
          ./bin/trivy image ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --format json --output anchore-reports/scan-report.json

      - name: Show Trivy Scan Results
        run: |
          cat anchore-reports/scan-report.json

      - name: Check for Vulnerabilities
        id: vulnerabilities-check
        run: |
          # Capture vulnerabilities count
          VULNERABILITIES=$(jq -r '.Vulnerabilities | length' anchore-reports/scan-report.json)
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "Vulnerabilities found in the Docker image:"
            jq -r '.Vulnerabilities[] | "  * \(.VulnerabilityID): \(.PkgName) (\(.InstalledVersion))"' anchore-reports/scan-report.json
            echo "::set-output name=vulnerabilities-found::true"
          else
            echo "No vulnerabilities found in the Docker image."
            echo "::set-output name=vulnerabilities-found::false"
          fi

      - name: Save Full Scan Report
        if: success()  # Guardar el reporte completo solo si el escaneo fue exitoso
        run: |
          cp anchore-reports/scan-report.json anchore-reports/full-scan-report.json

      - name: Create 'image-vulnerables' folder
        run: mkdir -p image-vulnerables

      - name: Move Scan Reports to 'image-vulnerables'
        run: |
          mv anchore-reports/scan-report.json image-vulnerables/
          mv anchore-reports/full-scan-report.json image-vulnerables/

      - name: Upload Scan Results
        if: success()  # Subir resultados solo si el escaneo fue exitoso y no se encontraron vulnerabilidades críticas
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports
          path: ./anchore-reports

      - name: Upload Vulnerable Image Reports
        if: steps.vulnerabilities-check.outputs.vulnerabilities-found == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: image-vulnerables
          path: ./image-vulnerables

      # Mostrar advertencia si se encontraron vulnerabilidades
      - name: Display Vulnerabilities as Warning
        if: steps.vulnerabilities-check.outputs.vulnerabilities-found == 'true'
        run: |
          echo "::warning::Vulnerabilities were found in the Docker image. Review the scan report for details."
