name: CI/CD Pipeline with Trivy

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Obtener el nombre de la imagen desde el Dockerfile
      - name: Get Docker Image Name
        id: get-image-name
        run: |
          IMAGE_NAME=$(awk '$1 == "FROM" { print $2; exit }' Dockerfile)
          echo "::set-output name=image-name::$IMAGE_NAME"

      # Construir la imagen Docker usando el Dockerfile del repositorio
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get-image-name.outputs.image-name }} .

      # Autenticación en Docker Hub
      - name: Login to Docker Hub
        if: success()  # Solo intentar login si la construcción de la imagen fue exitosa
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Verificar si la imagen ya existe en Docker Hub
      - name: Check if Image Exists on Docker Hub
        id: check-image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get-image-name.outputs.image-name }}
          docker pull $IMAGE_NAME || exit 0

      # Construir y subir la imagen solo si no existe en Docker Hub
      - name: Build and Push Docker Image
        if: steps.check-image.run == 'exit 0'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get-image-name.outputs.image-name }}

      # Instalar Trivy CLI
      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b ./bin

      # Escanear la imagen Docker con Trivy
      - name: Scan Docker Image with Trivy
        id: trivy-scan
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/myapp:${{ steps.get-image-name.outputs.image-name }}
          ./bin/trivy image $IMAGE_NAME --severity HIGH,MEDIUM,LOW --ignore-unfixed --format json --output docker-image-vul.json

      # Mostrar los resultados del escaneo si es necesario
      - name: Show Trivy Scan Results
        run: |
          cat docker-image-vul.json

      # Verificar vulnerabilidades encontradas
      - name: Check for Vulnerabilities
        id: vulnerabilities-check
        continue-on-error: true  # Continuar incluso si hay un error en este paso
        run: |
          # Capturar la cantidad de vulnerabilidades
          VULNERABILITIES=$(jq -r '.Vulnerabilities | length' docker-image-vul.json || echo "0")
          echo "Number of vulnerabilities found: $VULNERABILITIES"
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "Vulnerabilities found in the Docker image:"
            jq -r '.Vulnerabilities[] | "  * \(.VulnerabilityID): \(.PkgName) (\(.InstalledVersion))"' docker-image-vul.json
            echo "::set-output name=vulnerabilities-found::true"
          else
            echo "No vulnerabilities found in the Docker image."
            echo "::set-output name=vulnerabilities-found::false"
          fi

      # Guardar el reporte de escaneo en el repositorio
      - name: Save Scan Report to Repository
        if: success()  # Guardar el reporte solo si el escaneo fue exitoso
        run: |
          cp docker-image-vul.json ./docker-image-vul.json

      # Subir archivo de reporte como artefacto final
      - name: Upload Scan Report as Artifact
        if: success()  # Subir solo si el escaneo fue exitoso
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-vul-report
          path: ./docker-image-vul.json

      # Mostrar advertencia si se encontraron vulnerabilidades
      - name: Display Vulnerabilities as Warning
        if: steps.vulnerabilities-check.outputs.vulnerabilities-found == 'true'
        run: |
          echo "::warning::Vulnerabilities were found in the Docker image. Review the scan report for details."
